--
-- PostgreSQL database dump
--

-- Dumped from database version 17.1
-- Dumped by pg_dump version 17.1

-- Started on 2025-07-01 01:12:21

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 74153)
-- Name: emotions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.emotions (
    id integer NOT NULL,
    journal_id integer NOT NULL,
    emotion bytea,
    created_time timestamp with time zone
);


ALTER TABLE public.emotions OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 74190)
-- Name: emotions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.emotions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emotions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 74122)
-- Name: journals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.journals (
    id integer NOT NULL,
    journal_input bytea,
    feedback bytea,
    created_time timestamp with time zone
);


ALTER TABLE public.journals OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 74189)
-- Name: journals_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.journals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.journals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 74165)
-- Name: scores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.scores (
    id integer NOT NULL,
    journal_id integer NOT NULL,
    severity bytea,
    total_score bytea,
    score_type character varying,
    created_time timestamp with time zone
);


ALTER TABLE public.scores OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 74191)
-- Name: scores_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.scores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 74177)
-- Name: themes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.themes (
    id integer NOT NULL,
    journal_id integer NOT NULL,
    theme bytea,
    created_time timestamp with time zone
);


ALTER TABLE public.themes OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 74192)
-- Name: themes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.themes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.themes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4713 (class 2606 OID 74159)
-- Name: emotions emotions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emotions
    ADD CONSTRAINT emotions_pkey PRIMARY KEY (id);


--
-- TOC entry 4711 (class 2606 OID 74128)
-- Name: journals journals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.journals
    ADD CONSTRAINT journals_pkey PRIMARY KEY (id);


--
-- TOC entry 4715 (class 2606 OID 74171)
-- Name: scores scores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scores
    ADD CONSTRAINT scores_pkey PRIMARY KEY (id);


--
-- TOC entry 4717 (class 2606 OID 74183)
-- Name: themes themes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.themes
    ADD CONSTRAINT themes_pkey PRIMARY KEY (id);


--
-- TOC entry 4718 (class 2606 OID 74160)
-- Name: emotions emotion_journal_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emotions
    ADD CONSTRAINT emotion_journal_fk FOREIGN KEY (journal_id) REFERENCES public.journals(id);


--
-- TOC entry 4719 (class 2606 OID 74172)
-- Name: scores score_journal_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scores
    ADD CONSTRAINT score_journal_fk FOREIGN KEY (journal_id) REFERENCES public.journals(id);


--
-- TOC entry 4720 (class 2606 OID 74184)
-- Name: themes theme_journal_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.themes
    ADD CONSTRAINT theme_journal_fk FOREIGN KEY (journal_id) REFERENCES public.journals(id);


-- Completed on 2025-07-01 01:12:22

--
-- PostgreSQL database dump complete
--

